import { describe, expect, it } from "vitest";

import type { MatchEvent } from "@/db/schema";

import { type PeriodsConfig, periodOfClockMs, periodsConfig } from "./clock";
import type { MatchEventType } from "./events";
import type { SlotInfo } from "./lineup";
import {
  type MatchEventRecord,
  type MatchReducerConfig,
  type PlannedLineup,
  playerState,
  reduceMatch,
  reverseTimeline,
  toMatchPlayerStats,
} from "./reducer";

/* -------------------------------------------------------------------------- */
/* Fixtures                                                                   */
/* -------------------------------------------------------------------------- */

/** Wall clock of the kick-off. Only the live-match tests care about it. */
const T0 = Date.UTC(2026, 3, 11, 8, 0, 0);
const MIN = 60_000;

const SLOT = {
  gb: "s-gb",
  dg: "s-dg",
  dc: "s-dc",
  dd: "s-dd",
  mg: "s-mg",
  mc1: "s-mc1",
  mc2: "s-mc2",
  at: "s-at",
} as const;

/** The 1-3-2-1 of the seeded team, plus a left-midfield slot the anomaly fixtures need. */
const SLOTS: SlotInfo[] = [
  { id: SLOT.gb, positionCode: "GB", sort: 1 },
  { id: SLOT.dg, positionCode: "DG", sort: 2 },
  { id: SLOT.dc, positionCode: "DC", sort: 3 },
  { id: SLOT.dd, positionCode: "DD", sort: 4 },
  { id: SLOT.mg, positionCode: "MG", sort: 5 },
  { id: SLOT.mc1, positionCode: "MC", sort: 6 },
  { id: SLOT.mc2, positionCode: "MC", sort: 7 },
  { id: SLOT.at, positionCode: "AT", sort: 8 },
];

const SQUAD = [
  { teamMemberId: "hugo", role: "starter" as const },
  { teamMemberId: "samir", role: "starter" as const },
  { teamMemberId: "thomas", role: "starter" as const },
  { teamMemberId: "nico", role: "starter" as const },
  { teamMemberId: "leo", role: "starter" as const },
  { teamMemberId: "karim", role: "starter" as const },
  { teamMemberId: "julien", role: "starter" as const },
  { teamMemberId: "momo", role: "substitute" as const },
  { teamMemberId: "yanis", role: "substitute" as const },
  { teamMemberId: "ali", role: "substitute" as const },
  { teamMemberId: "fabien", role: "substitute" as const },
  { teamMemberId: "gerard", role: "supporter" as const },
];

const CONFIG: MatchReducerConfig = { slots: SLOTS, squad: SQUAD };

type Fixture = {
  type: MatchEventType;
  min: number;
  /** Defaults to the period the match time falls in; passed explicitly at a boundary. */
  period?: number;
  payload?: unknown;
  /** 1-based index of the event this one annuls. */
  voids?: number;
};

/**
 * Build a log the way the database holds one: `clock_ms` in match time, `seq` in the order the
 * device produced the events, ids `e1…`. Every test builds its fixture by hand — a log generated by
 * the same code that reduces it would prove nothing.
 */
function log(fixtures: Fixture[], periods?: Partial<PeriodsConfig>): MatchEventRecord[] {
  const config = periodsConfig(periods);
  return fixtures.map((fixture, index) => ({
    id: `e${index + 1}`,
    clientEventId: `c${index + 1}`,
    type: fixture.type,
    period: fixture.period ?? periodOfClockMs(fixture.min * MIN, config),
    minute: fixture.min,
    clockMs: fixture.min * MIN,
    occurredAt: new Date(T0 + fixture.min * MIN),
    payload: fixture.payload ?? {},
    voidsEventId: fixture.voids === undefined ? null : `e${fixture.voids}`,
    seq: index + 1,
  }));
}

const lineupPayload = (pairs: Record<string, string>, lineupId?: string) => ({
  lineupId: lineupId ?? null,
  slots: Object.entries(pairs).map(([slotId, memberId]) => ({ slotId, memberId })),
});

const STARTING_ELEVEN = {
  [SLOT.gb]: "hugo",
  [SLOT.dg]: "samir",
  [SLOT.dc]: "thomas",
  [SLOT.dd]: "nico",
  [SLOT.mc1]: "leo",
  [SLOT.mc2]: "karim",
  [SLOT.at]: "julien",
};

/**
 * The log `db/seed.ts` writes for the two finished matches, event for event. If this fixture and the
 * seed ever disagree, one of them is wrong — which is the point of keeping it here in full.
 */
const SEED_LOG = log([
  { type: "KICKOFF", min: 0, period: 1 },
  { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN, "l-initial") },
  { type: "GOAL_FOR", min: 11, payload: { scorerId: "julien", assistId: "karim" } },
  { type: "FOUL", min: 19, payload: { memberId: "thomas" } },
  { type: "GOAL_AGAINST", min: 24 },
  { type: "GOAL_FOR", min: 27, payload: { scorerId: "leo" } },
  { type: "VOID", min: 27, voids: 6 },
  { type: "GOAL_FOR", min: 28, payload: { scorerId: "karim", assistId: "leo" } },
  { type: "PERIOD_END", min: 30, period: 1 },
  { type: "KICKOFF", min: 30, period: 2 },
  { type: "SUBSTITUTION", min: 38, payload: { outId: "leo", inId: "yanis", slotId: SLOT.mc1 } },
  { type: "PENALTY_SCORED", min: 44, payload: { scorerId: "julien" } },
  { type: "OWN_GOAL", min: 51, payload: { scorerId: "nico" } },
  {
    type: "POSITION_CHANGE",
    min: 55,
    payload: { memberId: "karim", fromSlotId: SLOT.mc2, toSlotId: SLOT.at },
  },
  { type: "SUBSTITUTION", min: 55, payload: { outId: "julien", inId: "momo", slotId: SLOT.mc2 } },
  { type: "PENALTY_MISSED", min: 58, payload: { scorerId: "momo" } },
  { type: "PERIOD_END", min: 60, period: 2 },
  { type: "FINAL_WHISTLE", min: 60, period: 2 },
]);

const minutesOf = (state: ReturnType<typeof reduceMatch>) =>
  Object.fromEntries(state.players.map((player) => [player.memberId, player.minutes]));

/* -------------------------------------------------------------------------- */
/* The empty and the trivial                                                  */
/* -------------------------------------------------------------------------- */

describe("an empty log", () => {
  const state = reduceMatch([]);

  it("is a 0-0 that has not started, with no result", () => {
    expect(state.goalsFor).toBe(0);
    expect(state.goalsAgainst).toBe(0);
    expect(state.scoreLabel).toBe("0 – 0");
    expect(state.phase).toBe("before-kickoff");
    expect(state.started).toBe(false);
    expect(state.finished).toBe(false);
    // A match in progress has no result, and neither has one that never began.
    expect(state.result).toBeNull();
  });

  it("knows nothing about anybody and complains about nothing", () => {
    expect(state.players).toEqual([]);
    expect(state.onPitch).toEqual([]);
    expect(state.timeline).toEqual([]);
    expect(state.goalkeeperId).toBeNull();
    expect(state.anomalies).toEqual([]);
  });

  it("still reports the configured periods and a readable clock", () => {
    expect(state.periods).toEqual({ periodsCount: 2, periodMinutes: 30 });
    expect(state.reading.clock).toBe("00:00");
    expect(state.reading.label).toBe("0’");
  });

  it("lists the whole squad on the bench when it is given one", () => {
    const withSquad = reduceMatch([], [], CONFIG);
    expect(withSquad.players).toHaveLength(SQUAD.length);
    expect(withSquad.players.every((player) => player.minutes === 0)).toBe(true);
    expect(withSquad.players.every((player) => player.playedMatch === false)).toBe(true);
    // Supporters are in the squad but are not on the bench: they are not going to play.
    expect(withSquad.bench).toHaveLength(SQUAD.length - 1);
    expect(withSquad.bench).not.toContain("gerard");
  });
});

/* -------------------------------------------------------------------------- */
/* The seeded match                                                           */
/* -------------------------------------------------------------------------- */

describe("the seeded match, reduced", () => {
  const state = reduceMatch(SEED_LOG, [], CONFIG);

  it("finishes 3-2, a win", () => {
    // 11′ Julien, 28′ Karim, 44′ penalty Julien — the 27′ goal was annulled.
    expect(state.goalsFor).toBe(3);
    // 24′ conceded, 51′ own goal by Nico.
    expect(state.goalsAgainst).toBe(2);
    expect(state.scoreLabel).toBe("3 – 2");
    expect(state.result).toBe("win");
    expect(state.finished).toBe(true);
    expect(state.phase).toBe("finished");
    expect(state.periodsStarted).toBe(2);
  });

  it("has nothing to complain about", () => {
    // In particular, Karim taking the striker's slot at 55′ while Julien is still standing in it is
    // not an anomaly: a position change never displaces anybody (rule 6).
    expect(state.anomalies).toEqual([]);
  });

  it("gives every player the minutes he actually played", () => {
    expect(minutesOf(state)).toEqual({
      hugo: 60,
      samir: 60,
      thomas: 60,
      nico: 60,
      karim: 60,
      julien: 55,
      leo: 38,
      yanis: 22,
      momo: 5,
      ali: 0,
      fabien: 0,
      gerard: 0,
    });
  });

  it("credits goals, assists, own goals, penalties and fouls to the right players", () => {
    const julien = playerState(state, "julien")!;
    // A scored penalty is a goal *and* a penalty: the two fields must never be added together.
    expect(julien).toMatchObject({ goals: 2, penaltiesScored: 1, assists: 0 });
    expect(playerState(state, "karim")).toMatchObject({ goals: 1, assists: 1 });
    // Léo's only goal was annulled; his assist at 28′ stands.
    expect(playerState(state, "leo")).toMatchObject({ goals: 0, assists: 1 });
    expect(playerState(state, "nico")).toMatchObject({ ownGoals: 1, goals: 0 });
    expect(playerState(state, "momo")).toMatchObject({ penaltiesMissed: 1, goals: 0 });
    expect(playerState(state, "thomas")).toMatchObject({ fouls: 1 });

    const scored = state.players.reduce((total, player) => total + player.goals, 0);
    expect(scored).toBe(state.goalsFor);
  });

  it("counts clean minutes per spell, so a substitute's fresh start is not wasted", () => {
    // Everybody who started was on when we conceded at 24′: 24 clean minutes each, no more.
    expect(playerState(state, "samir")!.cleanMinutes).toBe(24);
    expect(playerState(state, "julien")!.cleanMinutes).toBe(24);
    // Yanis came on at 38′ with the sheet already broken, and kept his own until the own goal at 51′.
    expect(playerState(state, "yanis")!.cleanMinutes).toBe(13);
    // Momo came on at 55′ and conceded nothing at all.
    expect(playerState(state, "momo")).toMatchObject({ cleanMinutes: 5, concededWhileOn: 0 });
  });

  it("counts goals conceded while each player was on the pitch", () => {
    expect(playerState(state, "hugo")!.concededWhileOn).toBe(2);
    // Léo went off at 38′, so the own goal at 51′ is not on his record.
    expect(playerState(state, "leo")!.concededWhileOn).toBe(1);
    expect(playerState(state, "yanis")!.concededWhileOn).toBe(1);
  });

  it("knows who was in goal, and for how long he kept it clean", () => {
    expect(state.goalkeeperId).toBe("hugo");
    expect(playerState(state, "hugo")).toMatchObject({
      wasGoalkeeper: true,
      gkMinutes: 60,
      gkCleanMinutes: 24,
      concededWhileGk: 2,
    });
    expect(playerState(state, "samir")!.wasGoalkeeper).toBe(false);
    expect(playerState(state, "samir")!.gkMinutes).toBe(0);
  });

  it("follows each player's position over time", () => {
    const karim = playerState(state, "karim")!;
    expect(karim.positionSpells).toEqual([
      { slotId: SLOT.mc2, positionCode: "MC", fromClockMs: 0, toClockMs: 55 * MIN },
      { slotId: SLOT.at, positionCode: "AT", fromClockMs: 55 * MIN, toClockMs: null },
    ]);
    expect(karim.positionCode).toBe("AT");
    // Momo took the slot Karim vacated, which is what the substitution payload says.
    expect(playerState(state, "momo")!.positionCode).toBe("MC");
  });

  it("records a spell for a player who came on and went off again", () => {
    expect(playerState(state, "leo")!.spells).toEqual([{ fromClockMs: 0, toClockMs: 38 * MIN }]);
    expect(playerState(state, "yanis")!.spells).toEqual([
      { fromClockMs: 38 * MIN, toClockMs: null },
    ]);
    expect(playerState(state, "leo")!.onPitch).toBe(false);
    expect(playerState(state, "yanis")!.onPitch).toBe(true);
  });

  it("separates the eleven who started from those who came on", () => {
    const started = state.players.filter((player) => player.startedMatch).map((p) => p.memberId);
    expect(started.sort()).toEqual(["hugo", "julien", "karim", "leo", "nico", "samir", "thomas"]);
    expect(playerState(state, "momo")!.startedMatch).toBe(false);
    expect(playerState(state, "ali")!.playedMatch).toBe(false);
  });

  it("does not take anybody off at the final whistle — the state shows who finished the match", () => {
    expect(state.onPitch).toHaveLength(7);
    expect(state.onPitch.map((entry) => entry.memberId)).toEqual([
      "hugo",
      "samir",
      "thomas",
      "nico",
      "yanis",
      "momo",
      "karim",
    ]);
    expect(state.onPitch[0]).toMatchObject({ isGoalkeeper: true, sinceClockMs: 60 * MIN });
    expect([...state.bench].sort()).toEqual(["ali", "fabien", "leo", "julien"].sort());
  });

  it("keeps every event in the timeline, including the annulled goal and its annulment", () => {
    expect(state.timeline).toHaveLength(SEED_LOG.length);
    const annulled = state.timeline.find((entry) => entry.eventId === "e6")!;
    expect(annulled).toMatchObject({
      type: "GOAL_FOR",
      voided: true,
      voidedByEventId: "e7",
      minuteLabel: "27’",
      labelFr: "But",
      // It changed nothing, so it carries no score.
      scoreAfter: null,
    });
    const annulment = state.timeline.find((entry) => entry.eventId === "e7")!;
    expect(annulment).toMatchObject({ type: "VOID", voidsEventId: "e6", labelFr: "Annulation" });
    expect(state.voidedEventIds).toEqual(["e6"]);
  });

  it("carries the running score on the events that changed it", () => {
    const scores = state.timeline
      .filter((entry) => entry.scoreAfter !== null)
      .map((entry) => `${entry.minuteLabel} ${entry.scoreAfter!.goalsFor}-${entry.scoreAfter!.goalsAgainst}`);
    expect(scores).toEqual(["11’ 1-0", "24’ 1-1", "28’ 2-1", "44’ 3-1", "51’ 3-2"]);
  });

  it("names the players each timeline entry is about, without knowing their names", () => {
    const goal = state.timeline.find((entry) => entry.eventId === "e3")!;
    expect(goal.actors).toEqual([
      { memberId: "julien", role: "scorer" },
      { memberId: "karim", role: "assist" },
    ]);
    const substitution = state.timeline.find((entry) => entry.eventId === "e11")!;
    expect(substitution.actors).toEqual([
      { memberId: "leo", role: "out" },
      { memberId: "yanis", role: "in" },
    ]);
    const initial = state.timeline.find((entry) => entry.eventId === "e2")!;
    expect(initial.actors).toHaveLength(7);
    expect(initial.actors.every((actor) => actor.role === "in")).toBe(true);
  });

  it("notes when the goals went in", () => {
    expect(state.scoredAt).toEqual([11 * MIN, 28 * MIN, 44 * MIN]);
    expect(state.concededAt).toEqual([24 * MIN, 51 * MIN]);
  });

  it("records which planned composition was applied", () => {
    expect(state.appliedLineupIds).toEqual(["l-initial"]);
  });

  it("reduces the same log to the same state whatever order the rows arrive in", () => {
    // The outbox retries, so insertion order is meaningless: an event logged at 12′ can land after
    // one logged at 40′.
    const shuffled = [
      SEED_LOG[14],
      SEED_LOG[3],
      SEED_LOG[17],
      SEED_LOG[1],
      SEED_LOG[8],
      SEED_LOG[6],
      SEED_LOG[13],
      SEED_LOG[0],
      SEED_LOG[11],
      SEED_LOG[5],
      SEED_LOG[16],
      SEED_LOG[2],
      SEED_LOG[9],
      SEED_LOG[15],
      SEED_LOG[4],
      SEED_LOG[12],
      SEED_LOG[7],
      SEED_LOG[10],
    ];
    expect(shuffled).toHaveLength(SEED_LOG.length);
    expect(reduceMatch(shuffled, [], CONFIG)).toEqual(state);
  });

  it("maps onto the match_player_stats cache", () => {
    const rows = toMatchPlayerStats(state);
    expect(rows).toHaveLength(SQUAD.length);
    expect(rows.find((row) => row.teamMemberId === "julien")).toEqual({
      teamMemberId: "julien",
      minutes: 55,
      goals: 2,
      assists: 0,
      ownGoals: 0,
      penaltiesScored: 1,
      penaltiesMissed: 0,
      fouls: 0,
      gkMinutes: 0,
      cleanMinutes: 24,
      concededWhileOn: 2,
      gkCleanMinutes: 0,
      concededWhileGk: 0,
      squadRole: "starter",
    });
    // The keeper's two figures are the ones decision 018 added a column for: they are not
    // derivable from the field-player pair above, and this is the row that proves it.
    expect(rows.find((row) => row.teamMemberId === "hugo")).toMatchObject({
      gkMinutes: 60,
      gkCleanMinutes: 24,
      concededWhileGk: 2,
    });
  });

  it("can hand the timeline back newest first, as game mode shows it", () => {
    expect(reverseTimeline(state)[0].type).toBe("FINAL_WHISTLE");
  });
});

/* -------------------------------------------------------------------------- */
/* Minutes                                                                    */
/* -------------------------------------------------------------------------- */

describe("minutes played", () => {
  it("excludes half-time, so 20′ to 40′ is twenty minutes and not the length of the break", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo", [SLOT.mc1]: "leo" }) },
        { type: "SUBSTITUTION", min: 20, payload: { outId: "leo", inId: "yanis", slotId: SLOT.mc1 } },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "KICKOFF", min: 30, period: 2 },
        { type: "SUBSTITUTION", min: 40, payload: { outId: "yanis", inId: "leo", slotId: SLOT.mc1 } },
        { type: "PERIOD_END", min: 60, period: 2 },
        { type: "FINAL_WHISTLE", min: 60, period: 2 },
      ]),
      [],
      { slots: SLOTS },
    );
    expect(playerState(state, "yanis")!.minutes).toBe(20);
    // Léo has two spells: 0′→20′ and 40′→60′.
    expect(playerState(state, "leo")!.minutes).toBe(40);
    expect(playerState(state, "leo")!.spells).toEqual([
      { fromClockMs: 0, toClockMs: 20 * MIN },
      { fromClockMs: 40 * MIN, toClockMs: null },
    ]);
  });

  it("accrues nothing across a break or after the final whistle", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo" }) },
        { type: "PERIOD_END", min: 30, period: 1 },
        // No second kick-off: the log stops at half-time.
        { type: "FOUL", min: 30, period: 1, payload: { memberId: "hugo" } },
      ]),
      [],
      { slots: SLOTS },
    );
    expect(playerState(state, "hugo")!.minutes).toBe(30);
    expect(state.phase).toBe("break");
    expect(state.finished).toBe(false);
  });

  it("rounds to whole minutes rather than rounding every appearance up", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.at]: "julien" }) },
        { type: "SUBSTITUTION", min: 58, payload: { outId: "julien", inId: "momo", slotId: SLOT.at } },
        { type: "FINAL_WHISTLE", min: 60, period: 2 },
      ]),
      [],
      { slots: SLOTS },
    );
    // Two minutes and no more: broadcast football would say three, and a season of those would
    // inflate a bench player's total by a third.
    expect(playerState(state, "momo")).toMatchObject({ playedMs: 2 * MIN, minutes: 2 });
  });

  it("handles three periods, with the clock running straight through", () => {
    const threeTwenty = { periodsCount: 3, periodMinutes: 20 };
    const state = reduceMatch(
      log(
        [
          { type: "KICKOFF", min: 0, period: 1 },
          { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo", [SLOT.at]: "julien" }) },
          { type: "PERIOD_END", min: 20, period: 1 },
          { type: "KICKOFF", min: 20, period: 2 },
          { type: "GOAL_FOR", min: 25, payload: { scorerId: "julien" } },
          { type: "PERIOD_END", min: 40, period: 2 },
          { type: "KICKOFF", min: 40, period: 3 },
          { type: "SUBSTITUTION", min: 50, payload: { outId: "julien", inId: "momo", slotId: SLOT.at } },
          { type: "PERIOD_END", min: 60, period: 3 },
          { type: "FINAL_WHISTLE", min: 60, period: 3 },
        ],
        threeTwenty,
      ),
      [],
      { ...CONFIG, ...threeTwenty },
    );
    expect(state.periods).toEqual(threeTwenty);
    expect(state.periodsStarted).toBe(3);
    expect(playerState(state, "hugo")!.minutes).toBe(60);
    expect(playerState(state, "julien")!.minutes).toBe(50);
    expect(playerState(state, "momo")!.minutes).toBe(10);
    // Continuous minutes: the third period runs 40′→60′, and the goal in the second reads 25′.
    expect(state.timeline.find((entry) => entry.type === "GOAL_FOR")!.minuteLabel).toBe("25’");
  });
});

/* -------------------------------------------------------------------------- */
/* Clean minutes                                                              */
/* -------------------------------------------------------------------------- */

describe("clean minutes", () => {
  it("gives a field player who was off the pitch when we conceded a clean second spell", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo", [SLOT.mc1]: "leo" }) },
        { type: "SUBSTITUTION", min: 20, payload: { outId: "leo", inId: "yanis", slotId: SLOT.mc1 } },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "KICKOFF", min: 30, period: 2 },
        { type: "GOAL_AGAINST", min: 35 },
        { type: "SUBSTITUTION", min: 40, payload: { outId: "yanis", inId: "leo", slotId: SLOT.mc1 } },
        { type: "PERIOD_END", min: 60, period: 2 },
        { type: "FINAL_WHISTLE", min: 60, period: 2 },
      ]),
      [],
      { slots: SLOTS },
    );
    // Léo was on the bench at 35′, so both of his spells are clean: all forty of his minutes count.
    expect(playerState(state, "leo")).toMatchObject({
      minutes: 40,
      cleanMinutes: 40,
      concededWhileOn: 0,
    });
    // Yanis was on: his clean minutes stop at the goal.
    expect(playerState(state, "yanis")).toMatchObject({
      minutes: 20,
      cleanMinutes: 15,
      concededWhileOn: 1,
    });
    // Hugo never left, so his sheet stays broken from 35′ on.
    expect(playerState(state, "hugo")).toMatchObject({ minutes: 60, cleanMinutes: 35 });
  });

  it("splits a goalkeeper's clean sheet when the keeper changes mid-match", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo", [SLOT.mc1]: "leo" }) },
        { type: "GOAL_AGAINST", min: 20 },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "KICKOFF", min: 30, period: 2 },
        { type: "SUBSTITUTION", min: 30, period: 2, payload: { outId: "hugo", inId: "momo", slotId: SLOT.gb } },
        { type: "GOAL_AGAINST", min: 50 },
        { type: "PERIOD_END", min: 60, period: 2 },
        { type: "FINAL_WHISTLE", min: 60, period: 2 },
      ]),
      [],
      { slots: SLOTS },
    );
    expect(playerState(state, "hugo")).toMatchObject({
      gkMinutes: 30,
      gkCleanMinutes: 20,
      concededWhileGk: 1,
    });
    // Momo starts a clean sheet of his own at 30′ and keeps it for twenty minutes.
    expect(playerState(state, "momo")).toMatchObject({
      gkMinutes: 30,
      gkCleanMinutes: 20,
      concededWhileGk: 1,
      wasGoalkeeper: true,
    });
    // Léo played all sixty and conceded twice; his own clean minutes stopped at the first goal.
    expect(playerState(state, "leo")).toMatchObject({
      minutes: 60,
      cleanMinutes: 20,
      concededWhileOn: 2,
      wasGoalkeeper: false,
    });
    expect(state.goalkeeperId).toBe("momo");
  });

  it("gives an outfield player who goes in goal a fresh sheet, and stops his old one", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo", [SLOT.mc1]: "leo" }) },
        { type: "GOAL_AGAINST", min: 10 },
        { type: "SUBSTITUTION", min: 20, payload: { outId: "hugo", inId: "momo", slotId: SLOT.mc1 } },
        { type: "POSITION_CHANGE", min: 20, payload: { memberId: "leo", fromSlotId: SLOT.mc1, toSlotId: SLOT.gb } },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "FINAL_WHISTLE", min: 30, period: 1 },
      ]),
      [],
      { slots: SLOTS },
    );
    const leo = playerState(state, "leo")!;
    expect(leo).toMatchObject({ minutes: 30, gkMinutes: 10, wasGoalkeeper: true });
    // His spell on the pitch conceded at 10′, but his spell in goal never did.
    expect(leo.cleanMinutes).toBe(10);
    expect(leo.gkCleanMinutes).toBe(10);
    expect(leo.concededWhileGk).toBe(0);
  });

  it("treats an own goal as a goal conceded, clean sheet and all", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo", [SLOT.dc]: "thomas" }) },
        { type: "OWN_GOAL", min: 10, payload: { scorerId: "thomas" } },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "FINAL_WHISTLE", min: 30, period: 1 },
      ]),
      [],
      { slots: SLOTS },
    );
    expect(state.goalsAgainst).toBe(1);
    expect(state.goalsFor).toBe(0);
    expect(state.result).toBe("loss");
    expect(playerState(state, "thomas")).toMatchObject({ ownGoals: 1, goals: 0, cleanMinutes: 10 });
    expect(playerState(state, "hugo")).toMatchObject({ gkCleanMinutes: 10, concededWhileGk: 1 });
  });

  it("keeps everybody's sheet clean when the opponent scores in his own net", () => {
    // We track no opponent players, so an own goal in our favour is a GOAL_FOR with no scorer.
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo" }) },
        { type: "GOAL_FOR", min: 10, payload: {} },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "FINAL_WHISTLE", min: 30, period: 1 },
      ]),
      [],
      { slots: SLOTS },
    );
    expect(state.goalsFor).toBe(1);
    expect(state.result).toBe("win");
    expect(playerState(state, "hugo")).toMatchObject({ gkCleanMinutes: 30, goals: 0 });
    expect(state.timeline.find((entry) => entry.type === "GOAL_FOR")!.actors).toEqual([]);
    expect(state.anomalies).toEqual([]);
  });

  it("calls a goalless draw a draw, and a clean sheet a clean sheet", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo" }) },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "KICKOFF", min: 30, period: 2 },
        { type: "PERIOD_END", min: 60, period: 2 },
        { type: "FINAL_WHISTLE", min: 60, period: 2 },
      ]),
      [],
      { slots: SLOTS },
    );
    expect(state.result).toBe("draw");
    expect(playerState(state, "hugo")).toMatchObject({
      gkMinutes: 60,
      gkCleanMinutes: 60,
      concededWhileGk: 0,
    });
  });
});

/* -------------------------------------------------------------------------- */
/* Positions and the pitch                                                    */
/* -------------------------------------------------------------------------- */

describe("the pitch", () => {
  it("moves a player without touching anybody else", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "POSITION_CHANGE", min: 20, payload: { memberId: "karim", fromSlotId: SLOT.mc2, toSlotId: SLOT.mg } },
      ]),
      [],
      CONFIG,
    );
    expect(state.onPitch).toHaveLength(7);
    expect(playerState(state, "karim")!.positionCode).toBe("MG");
    expect(playerState(state, "julien")!.positionCode).toBe("AT");
    expect(state.anomalies).toEqual([]);
  });

  it("supersedes the whole pitch when a composition is applied", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN, "l-1") },
        {
          type: "LINEUP_APPLIED",
          min: 30,
          period: 2,
          payload: lineupPayload(
            {
              ...STARTING_ELEVEN,
              [SLOT.gb]: "leo",
              [SLOT.mc1]: "julien",
              [SLOT.at]: "momo",
            },
            "l-2",
          ),
        },
      ]),
      [],
      CONFIG,
    );
    // The chained case, applied from the log rather than from a diff: one player off, one on, two
    // continuing players in new slots.
    expect(playerState(state, "hugo")!.onPitch).toBe(false);
    expect(playerState(state, "hugo")!.minutes).toBe(30);
    expect(playerState(state, "momo")!.positionCode).toBe("AT");
    expect(playerState(state, "leo")!.positionCode).toBe("GB");
    expect(playerState(state, "leo")!.wasGoalkeeper).toBe(true);
    expect(playerState(state, "julien")!.positionCode).toBe("MC");
    expect(state.onPitch).toHaveLength(7);
    expect(state.appliedLineupIds).toEqual(["l-1", "l-2"]);
    expect(state.anomalies).toEqual([]);
  });

  it("puts a substitute in the slot the outgoing player vacated when the payload says nothing", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload({ [SLOT.gb]: "hugo", [SLOT.at]: "julien" }) },
        // « Momo pour Julien », with no slot: the quick substitution does not always ask where.
        { type: "SUBSTITUTION", min: 20, payload: { outId: "julien", inId: "momo" } },
      ]),
      [],
      { slots: SLOTS },
    );
    expect(playerState(state, "momo")!.slotId).toBe(SLOT.at);
    expect(playerState(state, "momo")!.positionCode).toBe("AT");
  });
});

/* -------------------------------------------------------------------------- */
/* The clock                                                                  */
/* -------------------------------------------------------------------------- */

describe("a match in progress", () => {
  const liveLog = log([
    { type: "KICKOFF", min: 0, period: 1 },
    { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
    { type: "GOAL_FOR", min: 11, payload: { scorerId: "julien" } },
  ]);

  it("runs the clock and the minutes up to now", () => {
    const state = reduceMatch(liveLog, [], { ...CONFIG, nowMs: T0 + 24 * MIN });
    expect(state.phase).toBe("running");
    expect(state.reading.minute).toBe(24);
    expect(state.reading.running).toBe(true);
    expect(state.finished).toBe(false);
    // A match in progress has no result, whatever the score.
    expect(state.result).toBeNull();
    expect(playerState(state, "hugo")!.minutes).toBe(24);
    expect(playerState(state, "hugo")!.cleanMinutes).toBe(24);
  });

  it("stops at the last event when no wall clock is supplied", () => {
    // A server render with no clock is not allowed to invent minutes.
    const state = reduceMatch(liveLog, [], CONFIG);
    expect(state.reading.minute).toBe(11);
    expect(playerState(state, "hugo")!.minutes).toBe(11);
  });

  it("freezes everything while the clock is paused", () => {
    const paused = log([
      { type: "KICKOFF", min: 0, period: 1 },
      { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
      { type: "PAUSE", min: 10, payload: { reason: "joueur au sol" } },
    ]);
    const state = reduceMatch(paused, [], { ...CONFIG, nowMs: T0 + 25 * MIN });
    expect(state.phase).toBe("paused");
    expect(state.reading.minute).toBe(10);
    // Fifteen minutes of wall clock have passed and nobody has played a second of them.
    expect(playerState(state, "hugo")!.minutes).toBe(10);
  });

  it("resumes where it stopped: a pause consumes no match time", () => {
    const resumed = log([
      { type: "KICKOFF", min: 0, period: 1 },
      { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
      { type: "PAUSE", min: 10 },
      { type: "RESUME", min: 10 },
      { type: "PERIOD_END", min: 30, period: 1 },
      { type: "FINAL_WHISTLE", min: 30, period: 1 },
    ]);
    const state = reduceMatch(resumed, [], CONFIG);
    expect(playerState(state, "hugo")!.minutes).toBe(30);
    expect(state.playIntervals).toEqual([
      { period: 1, startMs: 0, endMs: 10 * MIN },
      { period: 1, startMs: 10 * MIN, endMs: 30 * MIN },
    ]);
    expect(state.anomalies).toEqual([]);
  });

  it("is between periods at half-time, and waiting for a whistle after the last one", () => {
    const halfTime = log([
      { type: "KICKOFF", min: 0, period: 1 },
      { type: "PERIOD_END", min: 30, period: 1 },
    ]);
    expect(reduceMatch(halfTime, [], CONFIG).phase).toBe("break");
    expect(reduceMatch(halfTime, [], CONFIG).reading.awaitingFinalWhistle).toBe(false);

    const fullTime = log([
      { type: "KICKOFF", min: 0, period: 1 },
      { type: "PERIOD_END", min: 30, period: 1 },
      { type: "KICKOFF", min: 30, period: 2 },
      { type: "PERIOD_END", min: 60, period: 2 },
    ]);
    expect(reduceMatch(fullTime, [], CONFIG).reading.awaitingFinalWhistle).toBe(true);
  });
});

/* -------------------------------------------------------------------------- */
/* Voids                                                                      */
/* -------------------------------------------------------------------------- */

describe("annulled events", () => {
  it("removes a goal from the score, from its scorer and from the assist", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "GOAL_FOR", min: 27, payload: { scorerId: "leo", assistId: "karim" } },
        { type: "VOID", min: 27, voids: 3 },
      ]),
      [],
      CONFIG,
    );
    expect(state.goalsFor).toBe(0);
    expect(state.scoredAt).toEqual([]);
    expect(playerState(state, "leo")).toMatchObject({ goals: 0 });
    expect(playerState(state, "karim")).toMatchObject({ assists: 0 });
    // But both lines are still there, so the UI can strike the goal through.
    expect(state.timeline).toHaveLength(4);
    expect(state.timeline[2].voided).toBe(true);
    expect(state.timeline[3].type).toBe("VOID");
  });

  it("undoes a substitution that never happened", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "SUBSTITUTION", min: 20, payload: { outId: "leo", inId: "yanis", slotId: SLOT.mc1 } },
        { type: "VOID", min: 20, voids: 3 },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "FINAL_WHISTLE", min: 30, period: 1 },
      ]),
      [],
      CONFIG,
    );
    expect(playerState(state, "leo")!.minutes).toBe(30);
    expect(playerState(state, "yanis")!.minutes).toBe(0);
    expect(playerState(state, "yanis")!.playedMatch).toBe(false);
  });

  it("puts a goal back on the board by appending it again, not by annulling the annulment", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "GOAL_FOR", min: 27, payload: { scorerId: "leo" } },
        { type: "VOID", min: 27, voids: 3 },
        // A VOID on a VOID is refused, and the goal stays annulled.
        { type: "VOID", min: 28, voids: 4 },
        { type: "GOAL_FOR", min: 29, payload: { scorerId: "leo" } },
      ]),
      [],
      CONFIG,
    );
    expect(state.goalsFor).toBe(1);
    expect(playerState(state, "leo")!.goals).toBe(1);
    expect(state.anomalies.map((anomaly) => anomaly.code)).toEqual(["void-targets-void"]);
  });

  it("says so when the event it annuls is not in the log, and changes nothing", () => {
    const events = log([
      { type: "KICKOFF", min: 0, period: 1 },
      { type: "GOAL_FOR", min: 11, payload: {} },
    ]);
    const orphan: MatchEventRecord = {
      ...events[1],
      id: "e-void",
      type: "VOID",
      payload: {},
      voidsEventId: "an-event-still-in-the-outbox",
      seq: 9,
    };
    const state = reduceMatch([...events, orphan], [], CONFIG);
    expect(state.goalsFor).toBe(1);
    expect(state.anomalies.map((anomaly) => anomaly.code)).toEqual(["void-target-unknown"]);
  });

  it("refuses to annul the same event twice", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "GOAL_FOR", min: 11, payload: {} },
        { type: "VOID", min: 11, voids: 2 },
        { type: "VOID", min: 12, voids: 2 },
      ]),
      [],
      CONFIG,
    );
    expect(state.goalsFor).toBe(0);
    expect(state.anomalies.map((anomaly) => anomaly.code)).toEqual(["duplicate-void"]);
  });

  it("complains when a VOID has no target, or when something else claims one", () => {
    const events = log([
      { type: "KICKOFF", min: 0, period: 1 },
      { type: "GOAL_FOR", min: 11, payload: {} },
    ]);
    const bareVoid: MatchEventRecord = { ...events[1], id: "e-void", type: "VOID", payload: {}, seq: 8 };
    const confused: MatchEventRecord = { ...events[1], id: "e-goal-2", voidsEventId: "e1", seq: 9 };
    const state = reduceMatch([...events, bareVoid, confused], [], CONFIG);
    expect(state.anomalies.map((anomaly) => anomaly.code).sort()).toEqual([
      "void-without-target",
      "voids-on-non-void",
    ]);
    // The confused goal is still counted: only a VOID's own target is in doubt.
    expect(state.goalsFor).toBe(2);
  });
});

/* -------------------------------------------------------------------------- */
/* Anomalies                                                                  */
/* -------------------------------------------------------------------------- */

describe("a log that cannot be true", () => {
  const codes = (state: ReturnType<typeof reduceMatch>) =>
    state.anomalies.map((anomaly) => anomaly.code);

  it("still counts a goal whose payload is unreadable", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "PENALTY_SCORED", min: 44, payload: { scorerId: 42 } },
      ]),
      [],
      CONFIG,
    );
    // A team's score is not allowed to depend on a device writing a number where a string belongs.
    expect(state.goalsFor).toBe(1);
    expect(codes(state)).toEqual(["invalid-payload"]);
    expect(state.timeline[2].invalidPayload).toBe(true);
    expect(state.timeline[2].actors).toEqual([]);
  });

  it("does nothing at all with a player-only event that names no player", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "FOUL", min: 19, payload: {} },
      ]),
      [],
      CONFIG,
    );
    expect(state.players.every((player) => player.fouls === 0)).toBe(true);
    expect(codes(state)).toEqual(["invalid-payload"]);
  });

  it("notices a substitution that brings on a player who is already playing", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "SUBSTITUTION", min: 20, payload: { outId: "leo", inId: "karim", slotId: SLOT.mc1 } },
      ]),
      [],
      CONFIG,
    );
    expect(codes(state)).toContain("substitute-in-already-on");
    // Best effort: Karim is moved rather than cloned, so the pitch stays believable.
    expect(state.onPitch).toHaveLength(6);
    expect(playerState(state, "karim")!.slotId).toBe(SLOT.mc1);
  });

  it("notices a substitution that takes off a player who is not on the pitch", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "SUBSTITUTION", min: 20, payload: { outId: "ali", inId: "yanis", slotId: SLOT.mg } },
      ]),
      [],
      CONFIG,
    );
    expect(codes(state)).toContain("substitute-out-not-on");
    // And it notices the consequence: eight players.
    expect(codes(state)).toContain("too-many-on-pitch");
    expect(state.onPitch).toHaveLength(8);
  });

  it("notices a position change for somebody who is not playing", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "POSITION_CHANGE", min: 20, payload: { memberId: "ali", fromSlotId: SLOT.mg, toSlotId: SLOT.at } },
      ]),
      [],
      CONFIG,
    );
    expect(codes(state)).toEqual(["position-change-off-pitch"]);
    // Ali has a line because he is in the squad, but the log has not put him on the pitch.
    expect(playerState(state, "ali")).toMatchObject({ onPitch: false, playedMatch: false });
    expect(state.timeline[2].actors).toEqual([]);
  });

  it("notices a goal scored by somebody who is not on the pitch", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "GOAL_FOR", min: 20, payload: { scorerId: "ali" } },
      ]),
      [],
      CONFIG,
    );
    expect(codes(state)).toEqual(["scorer-off-pitch"]);
    // Reported, but counted: the ball did go in, and a stat nobody can explain is worse than one
    // that is merely odd.
    expect(state.goalsFor).toBe(1);
    expect(playerState(state, "ali")!.goals).toBe(1);
  });

  it("notices a goal before any kick-off", () => {
    const state = reduceMatch(
      log([
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "GOAL_FOR", min: 5, payload: { scorerId: "julien" } },
      ]),
      [],
      CONFIG,
    );
    expect(codes(state)).toEqual(["goal-before-kickoff"]);
    expect(state.goalsFor).toBe(1);
    // Nobody has played a minute, because the match has not started.
    expect(playerState(state, "julien")!.minutes).toBe(0);
  });

  it("notices a second kick-off, a stray period end, a second whistle and a late event", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "KICKOFF", min: 1, period: 1 },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "PERIOD_END", min: 31, period: 1 },
        { type: "FINAL_WHISTLE", min: 32, period: 2 },
        { type: "FINAL_WHISTLE", min: 33, period: 2 },
        { type: "FOUL", min: 34, period: 2, payload: { memberId: "thomas" } },
      ]),
      [],
      CONFIG,
    );
    // Both the second whistle and the foul that follows it are after the match ended.
    expect([...new Set(codes(state))]).toEqual([
      "kickoff-while-in-play",
      "period-end-while-stopped",
      "duplicate-final-whistle",
      "event-after-final-whistle",
    ]);
    expect(codes(state).filter((code) => code === "event-after-final-whistle")).toHaveLength(2);
    expect(state.periodsStarted).toBe(1);
  });

  it("flags a composition that assigns one slot twice", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        {
          type: "LINEUP_APPLIED",
          min: 0,
          period: 1,
          payload: {
            lineupId: null,
            slots: [
              { slotId: SLOT.gb, memberId: "hugo" },
              { slotId: SLOT.gb, memberId: "momo" },
            ],
          },
        },
      ]),
      [],
      CONFIG,
    );
    expect(codes(state)).toContain("lineup-slot-conflict");
    // The first assignment wins; nobody is left in a slot with somebody else.
    expect(state.onPitch).toHaveLength(1);
  });

  it("flags a full team with nobody in goal", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        {
          type: "LINEUP_APPLIED",
          min: 0,
          period: 1,
          payload: lineupPayload({
            [SLOT.dg]: "samir",
            [SLOT.dc]: "thomas",
            [SLOT.dd]: "nico",
            [SLOT.mg]: "hugo",
            [SLOT.mc1]: "leo",
            [SLOT.mc2]: "karim",
            [SLOT.at]: "julien",
          }),
        },
      ]),
      [],
      CONFIG,
    );
    expect(codes(state)).toContain("no-goalkeeper-on-pitch");
    expect(state.goalkeeperId).toBeNull();
  });

  it("says once that it cannot identify the goalkeeper without a slot catalogue", () => {
    const state = reduceMatch(
      log([
        { type: "KICKOFF", min: 0, period: 1 },
        { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
        { type: "GOAL_AGAINST", min: 20 },
        { type: "SUBSTITUTION", min: 25, payload: { outId: "leo", inId: "yanis", slotId: SLOT.mc1 } },
        { type: "PERIOD_END", min: 30, period: 1 },
        { type: "FINAL_WHISTLE", min: 30, period: 1 },
      ]),
      [],
      { squad: SQUAD },
    );
    expect(codes(state)).toEqual(["goalkeeper-unknown"]);
    // Minutes and clean minutes are still exact: only the goalkeeping split is unavailable.
    expect(playerState(state, "hugo")).toMatchObject({
      minutes: 30,
      cleanMinutes: 20,
      gkMinutes: 0,
      gkCleanMinutes: 0,
    });
    expect(state.goalkeeperId).toBeNull();
  });
});

/* -------------------------------------------------------------------------- */
/* Planned compositions                                                       */
/* -------------------------------------------------------------------------- */

describe("planned compositions", () => {
  const events = log([
    { type: "KICKOFF", min: 0, period: 1 },
    { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN, "l-initial") },
    { type: "INJURY", min: 25, payload: { memberId: "thomas" } },
    { type: "PERIOD_END", min: 30, period: 1 },
    { type: "KICKOFF", min: 30, period: 2 },
  ]);

  const planned: PlannedLineup[] = [
    {
      id: "l-initial",
      fromMinute: 0,
      isInitial: true,
      appliedEventId: "e2",
      slots: Object.entries(STARTING_ELEVEN).map(([slotId, memberId]) => ({ slotId, memberId })),
    },
    {
      id: "l-second-half",
      fromMinute: 30,
      slots: Object.entries({ ...STARTING_ELEVEN, [SLOT.mc1]: "yanis" }).map(([slotId, memberId]) => ({
        slotId,
        memberId,
      })),
    },
  ];

  it("proposes the composition whose minute has come and waits for the coach", () => {
    // Decision 006: never applied automatically.
    const state = reduceMatch(events, planned, { ...CONFIG, nowMs: T0 + 32 * MIN });
    expect(state.pendingLineup?.lineupId).toBe("l-second-half");
    expect(state.pendingLineup?.due).toBe(true);
    expect(state.pendingLineup?.applied).toBe(false);
    expect(state.pendingLineup?.diff.substitutions).toEqual([
      { outId: "leo", inId: "yanis", slotId: SLOT.mc1, positionCode: "MC" },
    ]);
    // The pitch is untouched until a LINEUP_APPLIED says otherwise.
    expect(playerState(state, "yanis")!.minutes).toBe(0);
  });

  it("proposes nothing before the minute it is planned for", () => {
    const early = reduceMatch(events.slice(0, 3), planned, { ...CONFIG, nowMs: T0 + 20 * MIN });
    expect(early.pendingLineup).toBeNull();
    expect(early.plannedLineups[1].due).toBe(false);
  });

  it("knows the initial composition has already been applied", () => {
    const state = reduceMatch(events, planned, CONFIG);
    expect(state.plannedLineups[0]).toMatchObject({ lineupId: "l-initial", applied: true });
    expect(state.plannedLineups[0].diff.isEmpty).toBe(true);
  });

  it("flags a planned player who has been injured in this match", () => {
    const state = reduceMatch(events, planned, CONFIG);
    expect(state.plannedLineups[1].flags).toContainEqual({ memberId: "thomas", reason: "injured" });
  });

  it("flags a planned player who has already been substituted off", () => {
    const withSubstitution = [
      ...events,
      ...log([{ type: "SUBSTITUTION", min: 35, payload: { outId: "karim", inId: "momo", slotId: SLOT.mc2 } }]).map(
        (event) => ({ ...event, id: "e-sub", seq: 20 }),
      ),
    ];
    const laterPlan: PlannedLineup[] = [
      {
        id: "l-third",
        fromMinute: 40,
        slots: [{ slotId: SLOT.at, memberId: "karim" }],
      },
    ];
    const state = reduceMatch(withSubstitution, laterPlan, CONFIG);
    expect(state.plannedLineups[0].flags).toContainEqual({ memberId: "karim", reason: "already-off" });
  });

  it("flags a planned player who is not in the squad at all", () => {
    const state = reduceMatch(
      events,
      [{ id: "l-x", fromMinute: 30, slots: [{ slotId: SLOT.at, memberId: "a-stranger" }] }],
      CONFIG,
    );
    expect(state.plannedLineups[0].flags).toEqual([
      { memberId: "a-stranger", reason: "not-in-squad" },
    ]);
  });
});

/* -------------------------------------------------------------------------- */
/* Comments                                                                   */
/* -------------------------------------------------------------------------- */

describe("a comment", () => {
  const NOTE = "Coup franc dangereux, mur mal placé";

  /** Kept off the last minute of the log so that the two reductions anchor the clock identically. */
  const PLAYED: Fixture[] = [
    { type: "KICKOFF", min: 0, period: 1 },
    { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
    { type: "GOAL_FOR", min: 11, payload: { scorerId: "julien" } },
  ];

  const withComment = (payload: unknown) =>
    reduceMatch(
      log([...PLAYED.slice(0, 2), { type: "COMMENT", min: 5, payload }, ...PLAYED.slice(2)]),
      [],
      CONFIG,
    );

  it("changes nothing at all: not the score, not the clock, not the pitch, not the minutes", () => {
    const plain = reduceMatch(log(PLAYED), [], CONFIG);
    const commented = withComment({ note: NOTE });

    // Everything but the log itself is identical — a comment is a note in the margin, and this
    // compares the whole state rather than a chosen handful of fields.
    expect({ ...commented, timeline: [] }).toEqual({ ...plain, timeline: [] });
    expect(commented.goalsFor).toBe(1);
    expect(commented.goalsAgainst).toBe(0);
    expect(commented.onPitch).toHaveLength(7);
    expect(commented.anomalies).toEqual([]);
  });

  it("appears in the timeline carrying its note, and about nobody in particular", () => {
    const entry = withComment({ note: NOTE }).timeline.find((line) => line.type === "COMMENT")!;
    expect(entry.note).toBe(NOTE);
    expect(entry.labelFr).toBe("Commentaire");
    expect(entry.minuteLabel).toBe("5’");
    expect(entry.actors).toEqual([]);
    expect(entry.scoreAfter).toBeNull();
    expect(entry.invalidPayload).toBe(false);
  });

  it("attaches the player it is about, when the coach named one", () => {
    const entry = withComment({ note: NOTE, memberId: "karim" }).timeline.find(
      (line) => line.type === "COMMENT",
    )!;
    expect(entry.actors).toEqual([{ memberId: "karim", role: "commented" }]);
    expect(entry.note).toBe(NOTE);
  });

  it("leaves no note on any other event", () => {
    const state = reduceMatch(SEED_LOG, [], CONFIG);
    expect(state.timeline.every((entry) => entry.note === null)).toBe(true);
  });
});

/* -------------------------------------------------------------------------- */
/* Remarks                                                                    */
/* -------------------------------------------------------------------------- */

describe("a remark", () => {
  /** Same shape as the comment fixture above: kept off the last minute so the clocks anchor alike. */
  const PLAYED: Fixture[] = [
    { type: "KICKOFF", min: 0, period: 1 },
    { type: "LINEUP_APPLIED", min: 0, period: 1, payload: lineupPayload(STARTING_ELEVEN) },
    { type: "GOAL_FOR", min: 11, payload: { scorerId: "julien" } },
  ];

  const withRemark = (payload: unknown) =>
    reduceMatch(
      log([...PLAYED.slice(0, 2), { type: "REMARK", min: 5, payload }, ...PLAYED.slice(2)]),
      [],
      CONFIG,
    );

  const remarked = (payload: unknown) =>
    withRemark(payload).timeline.find((line) => line.type === "REMARK")!;

  it("changes nothing at all: not the score, not the clock, not the pitch, not the minutes", () => {
    const plain = reduceMatch(log(PLAYED), [], CONFIG);
    const state = withRemark({ kind: "GOOD_EFFORT", memberId: "karim" });

    // The whole state but the log itself, so no field can quietly start moving.
    expect({ ...state, timeline: [] }).toEqual({ ...plain, timeline: [] });
    expect(state.goalsFor).toBe(1);
    expect(state.goalsAgainst).toBe(0);
    expect(state.onPitch).toHaveLength(7);
    expect(state.anomalies).toEqual([]);
  });

  it("appears in the timeline with its kind and the player it names", () => {
    const entry = remarked({ kind: "GOOD_EFFORT", memberId: "karim" });
    expect(entry.remarkKind).toBe("GOOD_EFFORT");
    expect(entry.actors).toEqual([{ memberId: "karim", role: "remarked" }]);
    expect(entry.labelFr).toBe("Remarque");
    expect(entry.minuteLabel).toBe("5’");
    expect(entry.note).toBeNull();
    expect(entry.scoreAfter).toBeNull();
    expect(entry.invalidPayload).toBe(false);
  });

  /*
   * The degradation that matters, and the one the lenient schema exists for: the kind is a word
   * this build does not know, and the `memberId` beside it is perfectly good. Losing Karim with it
   * would be the reducer refusing a log Postgres has already accepted (decision 122), so the row
   * parses, names him, and has no kind to print.
   */
  it("names the player of a remark whose kind it does not know, and no kind", () => {
    const entry = remarked({ kind: "GOOD_HAIRCUT", memberId: "karim" });
    expect(entry.invalidPayload).toBe(false);
    expect(entry.remarkKind).toBeNull();
    expect(entry.actors).toEqual([{ memberId: "karim", role: "remarked" }]);
  });

  it("is still shown when its payload cannot be read, naming no kind and nobody", () => {
    // No `memberId`: a remark about nobody is not a remark, so this one really is unreadable.
    const entry = remarked({ kind: "GOOD_HAIRCUT" });
    expect(entry.invalidPayload).toBe(true);
    expect(entry.remarkKind).toBeNull();
    expect(entry.actors).toEqual([]);

    // And neither is a payload that is not an object at all.
    const garbage = remarked("GOOD_EFFORT");
    expect(garbage.invalidPayload).toBe(true);
    expect(garbage.remarkKind).toBeNull();
    expect(garbage.actors).toEqual([]);
  });

  it("leaves no remark kind on any other event", () => {
    const state = reduceMatch(SEED_LOG, [], CONFIG);
    expect(state.timeline.every((entry) => entry.remarkKind === null)).toBe(true);
  });
});

/* -------------------------------------------------------------------------- */
/* Contracts                                                                  */
/* -------------------------------------------------------------------------- */

describe("contracts", () => {
  it("accepts a row exactly as the database returns it", () => {
    // Compiles only if `MatchEvent` satisfies `MatchEventRecord` — including `occurredAt` as a Date.
    const asRecord = (row: MatchEvent): MatchEventRecord => row;
    expect(typeof asRecord).toBe("function");
  });

  it("accepts a log that crossed the RSC boundary as JSON", () => {
    const plain: MatchEventRecord[] = [
      {
        id: "e1",
        type: "KICKOFF",
        period: 1,
        minute: 0,
        clockMs: 0,
        occurredAt: "2026-04-11T08:00:00.000Z",
      },
      {
        id: "e2",
        type: "GOAL_FOR",
        period: 1,
        minute: 11,
        clockMs: 660_000,
        occurredAt: new Date(T0 + 11 * MIN).toISOString(),
        payload: { scorerId: "julien" },
      },
    ];
    const state = reduceMatch(plain, [], CONFIG);
    expect(state.goalsFor).toBe(1);
    expect(state.clock.anchoredAtMs).toBe(T0 + 11 * MIN);
  });

  it("never mutates the log it is given", () => {
    const events = log([
      { type: "KICKOFF", min: 0, period: 1 },
      { type: "GOAL_FOR", min: 11, payload: { scorerId: "julien" } },
    ]);
    const snapshot = JSON.stringify(events);
    reduceMatch(events.reverse(), [], CONFIG);
    expect(JSON.stringify([...events].reverse())).toBe(snapshot);
  });

  it("is deterministic: the same log reduces to the same state, twice", () => {
    expect(reduceMatch(SEED_LOG, [], CONFIG)).toEqual(reduceMatch(SEED_LOG, [], CONFIG));
  });

  it("falls back to 2×30 when the match configuration is missing", () => {
    const state = reduceMatch(SEED_LOG, [], { slots: SLOTS, periodsCount: null, periodMinutes: null });
    expect(state.periods).toEqual({ periodsCount: 2, periodMinutes: 30 });
  });
});
